esphome:
  name: stockdisplay
  platform: ESP8266
  board: esp_wroom_02

logger:
api:
ota:

wifi:
  ssid: !secret wifi_id
  password: !secret wifi_pw

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

sensor:
  - platform: homeassistant
    id: gme
    entity_id: sensor.gme_live_price
    internal: true
    on_value:
      then:
        - lambda: |-
            id(graph)[0] = id(graph)[1];
            id(graph)[1] = id(graph)[2];
            id(graph)[2] = id(graph)[3];

            if ((id(gme).state - id(old)) > id(threshold)) id(graph)[3] = '*';
            else if ((id(old) - id(gme).state) > id(threshold)) id(graph)[3] = '_';
            else id(graph)[3] = '-';

            id(segments).update();
            id(old) = id(gme).state;

text_sensor:
  - platform: homeassistant
    id: market
    entity_id: sensor.gme_live_state
    internal: true

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin

globals:
  - id: old
    type: float
    initial_value: "0"
  - id: graph
    type: char[5] # last char is array end symbol?
    initial_value: "{'-', '-', '-', '-'}"
  - id: threshold
    type: double
    initial_value: "0.15"

display:
  - platform: max7219
    id: segments
    cs_pin: GPIO15
    num_chips: 1
    lambda: |-
      if (id(market).state == "REGULAR") {
        it.set_intensity(4);
        it.print(4, id(graph));
        it.printf(0, "%.01f", id(gme).state);
      } else if (id(market).state == "POST" || id(market).state == "POSTPOST") {
        it.print(0, "        ");
      } else {
        if (id(sntp_time).now().is_valid()) {
          it.set_intensity(1);
          it.strftime(0,"    %H.%M", id(sntp_time).now());
        } else {
          it.print(0, "  ----  ");
        }
      }

# id(market).state: "REGULAR", "PRE", "PREPRE", "POST", "POSTPOST"